name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Icons for iOS style
  cupertino_icons: ^1.0.8

  # 📌 Required for API calls
  http: ^1.1.0

  # 📌 Required for picking images (camera & gallery)
  image_picker: ^1.0.4

  # 📌 Required for saving processed image to local storage
  path_provider: ^2.1.2

  # 📌 Required for permissions (Storage, Camera, etc.)
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 📌 Agar tum custom images/icons use karoge to uncomment karo:
 # assets:
